-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 11:35:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rubics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rubics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rubics` DEFAULT CHARACTER SET utf8 ;
USE `rubics` ;

-- -----------------------------------------------------
-- Table `rubics`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `birthdate` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `last_connection` DATETIME NOT NULL,
  `actif` TINYINT NOT NULL,
  `identifier_id` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `identifier_id` (`identifier_id`),
  KEY `identifier_id_2` (`identifier_id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `desciption` TEXT NOT NULL,
  `actif` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `budget` FLOAT NOT NULL,
  `id_category` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  INDEX `request_category0_FK` (`id_category` ASC),
  INDEX `fk_request_client1_idx` (`client_id` ASC),
  CONSTRAINT `request_category0_FK`
    FOREIGN KEY (`id_category`)
    REFERENCES `rubics`.`category` (`id`),
  CONSTRAINT `fk_request_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `rubics`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `actif` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `vat` VARCHAR(25) NOT NULL,
  `country` VARCHAR(25) NOT NULL,
  `locality` VARCHAR(25) NOT NULL,
  `zip_code` VARCHAR(25) NOT NULL,
  `street` VARCHAR(25) NOT NULL,
  `number` VARCHAR(25) NOT NULL,
  `comment` VARCHAR(250) NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  INDEX `fk_company_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_company_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `rubics`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `actif` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`identifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`identifier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `pwd` VARCHAR(50) NOT NULL,
  `secret_question` VARCHAR(250) NOT NULL,
  `secret_answer` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mail` (`mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `finished_at` TIMESTAMP NULL,
  `finalized` TINYINT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`id`, `request_id`),
  INDEX `fk_project_request1_idx` (`request_id` ASC),
  CONSTRAINT `fk_project_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `rubics`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `extension` VARCHAR(50) NOT NULL,
  `path` VARCHAR(250) NOT NULL,
  `project_id` INT NOT NULL,
  `project_request_id` INT NOT NULL,
  PRIMARY KEY (`id`, `project_id`, `project_request_id`),
  INDEX `fk_media_project1_idx` (`project_id` ASC, `project_request_id` ASC),
  CONSTRAINT `fk_media_project1`
    FOREIGN KEY (`project_id` , `project_request_id`)
    REFERENCES `rubics`.`project` (`id` , `request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `priority` INT NOT NULL,
  `pwd` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `actif` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `birthdate` DATE NOT NULL,
  `biography` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `actif` TINYINT NOT NULL,
  `id_team` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `employee_team_FK` (`id_team` ASC),
  INDEX `employee_role0_FK` (`id_role` ASC),
  CONSTRAINT `employee_team_FK`
    FOREIGN KEY (`id_team`)
    REFERENCES `rubics`.`team` (`id`),
  CONSTRAINT `employee_role0_FK`
    FOREIGN KEY (`id_role`)
    REFERENCES `rubics`.`role` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`Realizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`Realizes` (
  `project_id` INT NOT NULL,
  `project_request_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  INDEX `fk_Realizes_project1_idx` (`project_id` ASC, `project_request_id` ASC),
  INDEX `fk_Realizes_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_Realizes_project1`
    FOREIGN KEY (`project_id` , `project_request_id`)
    REFERENCES `rubics`.`project` (`id` , `request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Realizes_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `rubics`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rubics`.`Characterizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubics`.`Characterizes` (
  `skill_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  INDEX `fk_Characterizes_skill1_idx` (`skill_id` ASC),
  INDEX `fk_Characterizes_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_Characterizes_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `rubics`.`skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Characterizes_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `rubics`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
